// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsXaml.Wpf")>]
[<assembly: AssemblyProductAttribute("FsXaml")>]
[<assembly: AssemblyDescriptionAttribute("F# Tools for working with XAML Projects")>]
[<assembly: AssemblyVersionAttribute("3.1.4")>]
[<assembly: AssemblyFileVersionAttribute("3.1.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsXaml.Wpf"
    let [<Literal>] AssemblyProduct = "FsXaml"
    let [<Literal>] AssemblyDescription = "F# Tools for working with XAML Projects"
    let [<Literal>] AssemblyVersion = "3.1.4"
    let [<Literal>] AssemblyFileVersion = "3.1.4"
