// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsXaml.Wpf.TypeProvider")>]
[<assembly: AssemblyProductAttribute("FsXaml")>]
[<assembly: AssemblyDescriptionAttribute("F# Tools for working with XAML Projects")>]
[<assembly: AssemblyVersionAttribute("3.1.1")>]
[<assembly: AssemblyFileVersionAttribute("3.1.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsXaml.Wpf.TypeProvider"
    let [<Literal>] AssemblyProduct = "FsXaml"
    let [<Literal>] AssemblyDescription = "F# Tools for working with XAML Projects"
    let [<Literal>] AssemblyVersion = "3.1.1"
    let [<Literal>] AssemblyFileVersion = "3.1.1"
